### ISSUE TITLE
Create test scripts that define/clear experiments for automated testing

### ISSUE THREAD

**Issue by msandbothe** [CarnegieLearningWeb/educational-experiment-service#129]
Expand them to define a set of experiments. Ideally write these in python so they can be called from the Locust scripts.

In the short term, we're concerned with creating a standard environment for reproducing bugs, but this will lead into a maintainable unit testing process.

**Comment by ppratikcr7** [comment]
Hi @msandbothe,
There are a few strange things, we would like to get clarification about. While locust load testing, we had created a script where we first delete all the existing experiments in the development server and then we create a single experiment. Then we run the locust tasks that you had written in a sequential way using locust’s “SequentialTaskSet”. This sequential execution is done so as to try and complete a proper order of API calls in order to get a student enrolled in the experiment. (The order of API calls is here: https://pastebin.com/1wh2jNR9 ). What we observed from the execution logs (Logs for the api calls details from which we observed a few things: https://pastebin.com/HQFbkE08 ) that the “/init” APi is called twice for a student id “a799916b-492b-4335-8c06-1646b0d84386”. You can search in the logs. Can you let us know how is that possible that a same user id is initialized again. Also, while checking the locust report ( Locust Report: https://drive.google.com/file/d/1h6PkWmXtWQZOSje4eGfcVqRlTxZKyBn0/view?usp=sharing) we observed that we had 25 “/mark” API calls, which indicate that the enrollment count should increased to 25 but instead we see only 11 enrollments in the upgrade UI. Also, a lot of users where again and again calling the “/mark” experiment API. Is this the reason we have 11 students enrolled instead of 25?
![Screenshot 2021-04-13 at 10 34 13 PM](https://user-images.githubusercontent.com/33730817/114595892-86836c80-9cac-11eb-9a5c-756c301bce0d.png)

**Comment by msandbothe** [comment]
From Slack discussion
Michael: The locust script simulates the possibility for a student to have multiple login sessions. In the logic that determines what UUID to use for the init call, there is a probability that either a new or existing user is returned. This was meant to mimic how our software won't know if a student has been initialized in upgrade and will likely call init each time they login. (edited) 
Does init handle this properly, especially if the group sent over is different than the one sent in prior inits

Pratik: Hey Michael. Got it. So, the script is running fine I guess. I and Nirmal were actually trying to find out how many enrollments we get compared to the number of /mark API calls, which didnt matched, but with this reason, we feel the difference is due to multiple login and same user marking the experiment again.

**Comment by amurphy-cl** [comment]
@ppratikcr7 I think this is waiting on you to provide a PR

**Comment by ppratikcr7** [comment]
@amurphy-cl @msandbothe  From Slack discussion:
Please find the PR: https://github.com/CarnegieLearningWeb/educational-experiment-service/pull/141. Let me know in case of any issue.

**Comment by ppratikcr7** [comment]
Hi @amurphy-cl @msandbothe, I would like to raise a PR for some enhancements in the locust script for having a protocol variable to easily change host URL's in the script and would make a small change in your code where the instructionId fetched was a single character instead of a UUID. Also, group type is not necessary for individual experiment, so would remove that as well.
